[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "uvex-scheduler"
version = "0.1.0"
description = "UVEX scheduler notebooks and data products"
readme = "README.md"
requires-python = ">=3.12, <3.15"
dependencies = [
    "ipywidgets",
    "jupyterlab",
    "m4opt>=2.11.0",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "pytest-cov",
]

[tool.setuptools.packages.find]
include = ["uvex_transient_toolkit*"]

[tool.pytest.ini_options]
testpaths = ["uvex_transient_toolkit"]
