[project]
name = "uvex-scheduler"
version = "0.1.0"
description = "UVEX scheduler notebooks and data products"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "ipykernel",
    "ipywidgets",
    "m4opt>=2.0.1",
]
